name: Bump Version and Create Branch

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Read and bump version
        id: versioning
        run: |
          version=$(jq -r '.version' package.json)
          echo "Current version: $version"

          IFS='.' read -r major minor patch <<< "$version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit and push version bump
        env:
          GIT_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git checkout -b version/${{ steps.versioning.outputs.new_version }}

          jq --arg v "${{ steps.versioning.outputs.new_version }}" '.version = $v' package.json > tmp.json && mv tmp.json package.json

          git add package.json
          git commit -m "Bump version to ${{ steps.versioning.outputs.new_version }}"

          # Set remote with token (even though checkout used it)
          git remote set-url origin https://x-access-token:${GIT_AUTH_TOKEN}@github.com/${{ github.repository }}.git
          git push origin version/${{ steps.versioning.outputs.new_version }}
